/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1urd92aPUqK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
//import Link from "react-router-dom"
import img1 from "../Images/img1.jpg"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardContent, CardFooter, Card } from "@/components/ui/card"

export function Black() {
  return (
    (<div className="flex h-full w-full flex-col">
      <header
        className="flex h-16 items-center justify-between border-b bg-gray-100 px-6 dark:border-gray-800 dark:bg-gray-950">
        <div className="flex items-center gap-4">
          <a className="flex items-center gap-2 font-semibold" href="#">
            <GroupIcon className="h-6 w-6" />
            <span>Profile Manager</span>
          </a>
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button
              className="rounded-full border border-gray-200 w-8 h-8 dark:border-gray-800"
              size="icon"
              variant="ghost">
              <img
                alt="Avatar"
                className="rounded-full"
                height="32"
                src={img1}
                style={{
                  aspectRatio: "32/32",
                  objectFit: "cover",
                }}
                width="32" />
              <span className="sr-only">Toggle user menu</span>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuLabel>My Account</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Settings</DropdownMenuItem>
            <DropdownMenuItem>Logout</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </header>
      <main className="flex-1 overflow-auto bg-gray-100 px-6 py-8 dark:bg-gray-950">
        <div className="mx-auto flex max-w-5xl flex-col gap-8">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl font-bold">User Profiles</h1>
            <Button size="sm">
              <PlusIcon className="mr-2 h-4 w-4" />
              Add Profile
            </Button>
          </div>
          <div
            className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            <Card className="group">
              <CardContent className="flex flex-col items-center gap-4 p-6">
                <Avatar className="h-20 w-20">
                  <AvatarImage alt="Avatar" src={img1} />
                  <AvatarFallback>JP</AvatarFallback>
                </Avatar>
                <div className="text-center">
                  <h3 className="text-lg font-medium">John Doe</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Software Engineer</p>
                </div>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  John is a passionate software engineer with a keen eye for detail and a love for problem-solving.
                </p>
              </CardContent>
              <CardFooter className="flex justify-end gap-2">
                <Button size="sm" variant="outline">
                  <DeleteIcon className="h-4 w-4" />
                  Edit
                </Button>
                <Button color="destructive" size="sm" variant="outline">
                  <TrashIcon className="h-4 w-4" />
                  Delete
                </Button>
              </CardFooter>
            </Card>
            <Card className="group">
              <CardContent className="flex flex-col items-center gap-4 p-6">
                <Avatar className="h-20 w-20">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="text-center">
                  <h3 className="text-lg font-medium">Jane Doe</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Product Manager</p>
                </div>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Jane is a driven product manager with a passion for creating user-centric solutions.
                </p>
              </CardContent>
              <CardFooter className="flex justify-end gap-2">
                <Button size="sm" variant="outline">
                  <DeleteIcon className="h-4 w-4" />
                  Edit
                </Button>
                <Button color="destructive" size="sm" variant="outline">
                  <TrashIcon className="h-4 w-4" />
                  Delete
                </Button>
              </CardFooter>
            </Card>
            <Card className="group">
              <CardContent className="flex flex-col items-center gap-4 p-6">
                <Avatar className="h-20 w-20">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>SM</AvatarFallback>
                </Avatar>
                <div className="text-center">
                  <h3 className="text-lg font-medium">Sarah Miller</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">UI/UX Designer</p>
                </div>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Sarah is a talented UI/UX designer with a keen eye for aesthetics and user experience.
                </p>
              </CardContent>
              <CardFooter className="flex justify-end gap-2">
                <Button size="sm" variant="outline">
                  <DeleteIcon className="h-4 w-4" />
                  Edit
                </Button>
                <Button color="destructive" size="sm" variant="outline">
                  <TrashIcon className="h-4 w-4" />
                  Delete
                </Button>
              </CardFooter>
            </Card>
            <Card className="group">
              <CardContent className="flex flex-col items-center gap-4 p-6">
                <Avatar className="h-20 w-20">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>MJ</AvatarFallback>
                </Avatar>
                <div className="text-center">
                  <h3 className="text-lg font-medium">Michael Johnson</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Data Analyst</p>
                </div>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Michael is a data-driven analyst with a passion for extracting insights from complex datasets.
                </p>
              </CardContent>
              <CardFooter className="flex justify-end gap-2">
                <Button size="sm" variant="outline">
                  <DeleteIcon className="h-4 w-4" />
                  Edit
                </Button>
                <Button color="destructive" size="sm" variant="outline">
                  <TrashIcon className="h-4 w-4" />
                  Delete
                </Button>
              </CardFooter>
            </Card>
            <Card className="group">
              <CardContent className="flex flex-col items-center gap-4 p-6">
                <Avatar className="h-20 w-20">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>EM</AvatarFallback>
                </Avatar>
                <div className="text-center">
                  <h3 className="text-lg font-medium">Emily Martinez</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Marketing Specialist</p>
                </div>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Emily is a creative marketing specialist with a knack for developing engaging campaigns.
                </p>
              </CardContent>
              <CardFooter className="flex justify-end gap-2">
                <Button size="sm" variant="outline">
                  <DeleteIcon className="h-4 w-4" />
                  Edit
                </Button>
                <Button color="destructive" size="sm" variant="outline">
                  <TrashIcon className="h-4 w-4" />
                  Delete
                </Button>
              </CardFooter>
            </Card>
            <Card className="group">
              <CardContent className="flex flex-col items-center gap-4 p-6">
                <Avatar className="h-20 w-20">
                  <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
                  <AvatarFallback>DW</AvatarFallback>
                </Avatar>
                <div className="text-center">
                  <h3 className="text-lg font-medium">David Wilson</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Software Engineer</p>
                </div>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  David is a skilled software engineer with a passion for building robust and scalable applications.
                </p>
              </CardContent>
              <CardFooter className="flex justify-end gap-2">
                <Button size="sm" variant="outline">
                  <DeleteIcon className="h-4 w-4" />
                  Edit
                </Button>
                <Button color="destructive" size="sm" variant="outline">
                  <TrashIcon className="h-4 w-4" />
                  Delete
                </Button>
              </CardFooter>
            </Card>
          </div>
        </div>
      </main>
    </div>)
  );
}

function DeleteIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M20 5H9l-7 7 7 7h11a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2Z" />
      <line x1="18" x2="12" y1="9" y2="15" />
      <line x1="12" x2="18" y1="9" y2="15" />
    </svg>)
  );
}


function GroupIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 7V5c0-1.1.9-2 2-2h2" />
      <path d="M17 3h2c1.1 0 2 .9 2 2v2" />
      <path d="M21 17v2c0 1.1-.9 2-2 2h-2" />
      <path d="M7 21H5c-1.1 0-2-.9-2-2v-2" />
      <rect width="7" height="5" x="7" y="7" rx="1" />
      <rect width="7" height="5" x="10" y="12" rx="1" />
    </svg>)
  );
}


function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}


function TrashIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>)
  );
}
