/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QnBpP354aoK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { RadioGroupItem, RadioGroup } from "@/components/ui/radio-group"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Bsignup() {
  return (
    (<div className="mx-auto max-w-md space-y-6 py-12">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Sign Up</h1>
        <p className="text-gray-500 dark:text-gray-400">Join our platform as a Photographer or Event Organizer.</p>
      </div>
      <div className="space-y-4">
        <RadioGroup defaultValue="photographer">
          <div className="flex items-center justify-center gap-4">
            <Label
              className="flex cursor-pointer items-center space-x-3 rounded-md border border-gray-300 bg-white px-4 py-3 shadow-sm transition-colors hover:border-gray-400 dark:border-gray-700 dark:bg-gray-800 dark:hover:border-gray-600"
              htmlFor="photographer">
              <RadioGroupItem id="photographer" value="photographer" />
              <span className="text-base font-medium">I am a Photographer</span>
            </Label>
            <Label
              className="flex cursor-pointer items-center space-x-3 rounded-md border border-gray-300 bg-white px-4 py-3 shadow-sm transition-colors hover:border-gray-400 dark:border-gray-700 dark:bg-gray-800 dark:hover:border-gray-600"
              htmlFor="event-organizer">
              <RadioGroupItem id="event-organizer" value="event-organizer" />
              <span className="text-base font-medium">I am an Event Organizer</span>
            </Label>
          </div>
        </RadioGroup>
        <form className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="username">Username</Label>
              <Input id="username" placeholder="Enter your username" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input id="email" placeholder="Enter your email" required type="email" />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="contact">Contact Number</Label>
              <Input id="contact" placeholder="Enter your contact number" required type="tel" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="age">Age</Label>
              <Input id="age" placeholder="Enter your age" required type="number" />
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="location">Location</Label>
            <Input id="location" placeholder="Enter your location" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="image">Upload Image</Label>
            <Input id="image" type="file" />
          </div>
          <Button className="w-full" type="submit">
            Create Account
          </Button>
        </form>
      </div>
    </div>)
  );
}
