/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/OgAHHkRYiju
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function Languages() {
  return (
    (<section className="container mx-auto py-12 md:py-20">
      <div className="max-w-3xl mx-auto space-y-6 text-center">
        <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Choose Your Language</h2>
        <p className="text-gray-500 dark:text-gray-400">
          Select your preferred language to personalize your experience.
        </p>
      </div>
      <div
        className="mt-10 grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
        <div
          className="relative rounded-lg border border-gray-200 bg-white p-4 text-center shadow-sm hover:bg-gray-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800">
          <div
            className="flex h-12 w-12 items-center justify-center rounded-full bg-gray-100 text-gray-900 dark:bg-gray-800 dark:text-gray-50">
            <GlobeIcon className="h-6 w-6" />
          </div>
          <div className="mt-3 font-medium">English</div>
          <div
            className="absolute top-2 right-2 rounded-full bg-green-500 px-2 py-1 text-xs font-medium text-white">
            Current
          </div>
        </div>
        <div
          className="relative rounded-lg border border-gray-200 bg-white p-4 text-center shadow-sm hover:bg-gray-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800">
          <div
            className="flex h-12 w-12 items-center justify-center rounded-full bg-gray-100 text-gray-900 dark:bg-gray-800 dark:text-gray-50">
            <GlobeIcon className="h-6 w-6" />
          </div>
          <div className="mt-3 font-medium">Español</div>
        </div>
        <div
          className="relative rounded-lg border border-gray-200 bg-white p-4 text-center shadow-sm hover:bg-gray-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800">
          <div
            className="flex h-12 w-12 items-center justify-center rounded-full bg-gray-100 text-gray-900 dark:bg-gray-800 dark:text-gray-50">
            <GlobeIcon className="h-6 w-6" />
          </div>
          <div className="mt-3 font-medium">Français</div>
        </div>
        <div
          className="relative rounded-lg border border-gray-200 bg-white p-4 text-center shadow-sm hover:bg-gray-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800">
          <div
            className="flex h-12 w-12 items-center justify-center rounded-full bg-gray-100 text-gray-900 dark:bg-gray-800 dark:text-gray-50">
            <GlobeIcon className="h-6 w-6" />
          </div>
          <div className="mt-3 font-medium">Deutsch</div>
        </div>
        <div
          className="relative rounded-lg border border-gray-200 bg-white p-4 text-center shadow-sm hover:bg-gray-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800">
          <div
            className="flex h-12 w-12 items-center justify-center rounded-full bg-gray-100 text-gray-900 dark:bg-gray-800 dark:text-gray-50">
            <GlobeIcon className="h-6 w-6" />
          </div>
          <div className="mt-3 font-medium">Italiano</div>
        </div>
      </div>
      <div className="mt-8 flex justify-center">
        <Button>Apply Language</Button>
      </div>
    </section>)
  );
}

function GlobeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20" />
      <path d="M2 12h20" />
    </svg>)
  );
}
