/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/JYpz2de7KbI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Searchbar() {
  return (
    (<div className="flex items-center w-full max-w-md mx-auto ">
      <div className="relative flex-1 ">
      <form>
      <Input className="pr-12 w-full rounded-[2rem] text-white h-8 bg-black border-[grey] outline-[none]" placeholder="Search" type="search"/>
        <Button
          className="absolute right-2 top-1/2 -translate-y-1/2 h-6"
          type="submit"
          variant="ghost">
          
          <SearchIcon className="h-5 w-5 text-white" />
        </Button>
      </form>
       
      </div>
    </div>)
  );
}

function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}
